### ISSUE TITLE
Decrypted/uncompressed filesize does not match original file size

### ISSUE THREAD

**Issue by Sarjuuk** [triggerhappy187/PHP-MPQ#3]
sorry, another one
when doing the diff i noticed some audio files where missing. Enabling debug lead to this error.

I'm trying to pin down when and why this happens.

files affected where:
* sound/creature/mekkatorque/og_mekkatorque_event11.wav
* sound/creature/mekkatorque/og_mekkatorque_event21.wav
* sound/creature/thermaplugg/og_thermaplugg_event04.wav

**Comment by cipherxof** [comment]
Many audio files use an unsupported compression. I added a debug message for this in the newest commit.
