### ISSUE TITLE
Found compresstion type: 105, Found compresstion type: 114....Warning: gzinflate(): data error in mpq.php on line 518

### ISSUE THREAD

**Issue by Karaulov** [triggerhappy187/PHP-MPQ#4]
Error1:

**Got 982 bytes of sector data
Found compresstion type: 2
Decompressed with gzip
Got 24 bytes of sector data
Found compresstion type: 105**

**Warning: gzinflate(): data error in C:\Openserver\OSPanel\domains\localhost\MapUploader\TriggerHappyMPQreader\mpq.php on line 518
Failed to decompress with gzip**

Error2: 

**Unsupported compression type: 8 (PKWARE)
Decrypted/uncompressed filesize(367) does not match original file size(641)**

**Comment by triggerhappy187** [comment]
Can you share the MPQ file you were testing with?

**Comment by Karaulov** [comment]
**Warning: gzinflate(): data error in C:\Openserver\OSPanel\domains\localhost\MapUploader\TriggerHappyMPQreader\mpq.php on line 516
./MapList/(2)MeltingValley.w3x:war3map.w3i**

**Comment by Karaulov** [comment]
With debug i see error: **Unsupported compression type: 8 (PKWARE)**

**Comment by Karaulov** [comment]
I try to add try{}catch{} but allways get error **gzinflate(): data error**
possible to add check for gz compression ? or what i got this error while extract files from mpq

**Comment by Karaulov** [comment]
File extracted but it print this errror if echo not disabled.

**Comment by triggerhappy187** [comment]
I don't have this issue when extracting "war3map.w3i" from "(2)MeltingValley.w3x". 

If you are using a RoC beta map, most of those use an unsupported compression.
