### ISSUE TITLE
Support protected maps

### ISSUE THREAD

**Issue by Karaulov** [triggerhappy187/PHP-MPQ#6]
Some maps can't be opened by PHP-MPQ with header error.

But I upload map to your demo version without error. 

Fantasmagoria v9

**Comment by Karaulov** [comment]
**
Warning: unpack(): Type V: not enough input, need 4, have 0 in ...\MapUploader\TriggerHappyMPQreader\mpq.reader.php on line 58

Warning: unpack(): Type V: not enough input, need 4, have 0 in ...\MapUploader\TriggerHappyMPQreader\mpq.reader.php on line 58**

Thiss error 100+ times .... :(

**Comment by triggerhappy187** [comment]
This should be fixed now in the newest commit. The problem was that the blocktable size was bigger than the file itself. I added a bounds check for that, and it solved the issue.

https://github.com/triggerhappy187/PHP-MPQ/commit/bc34737ba3654b31087d31f363c480c82367a44a

**Comment by Karaulov** [comment]
Thanks
