### ISSUE TITLE
Can't upload this map, please fix:

### ISSUE THREAD

**Issue by Karaulov** [triggerhappy187/PHP-MPQ#9]
**FOCS English Ver. 7.6.1**

![qrnrxkg 1](https://user-images.githubusercontent.com/6445336/33314116-b3e29c18-d43d-11e7-9186-76178062e450.png)

**Comment by Karaulov** [comment]
Download link: http://rgho.st/private/8tSXbPWDG/e575ef6898151b13ec176af2e206f4d0

Need fix this problem, please.

**Comment by Karaulov** [comment]
Error in debug mode: 
**Decrypted/uncompressed filesize(262192) does not match original file size(262188)**

**Comment by triggerhappy187** [comment]
This issue is fixed in https://github.com/triggerhappy187/PHP-MPQ/commit/ec26fd5ce78ed50526f3db0b28f396631294d49f, thanks for the map.
